### ISSUE TITLE
Get rid of commented-out code in sound_field_synthesis.py example

### ISSUE THREAD

**Issue by mgeier** [sfstoolbox/sfs-python#108]
The example script [sound_field_synthesis.py](../blob/master/doc/examples/sound_field_synthesis.py) currently contains a lot of code that's commented out.

This is very hard to maintain and not very helpful anyway.

Our goal should be that all code in the repository is run at least once during CI. This can't happen if it's commented out.

The commented lines of code should either be un-commented and turned into new example plots or they should be completely removed.

We could also split the example script into multiple parts and turn some of them into notebooks?

**Comment by fs446** [comment]
At the moment (large changes) I appreciate this file, since the changes could be adapted and checked in a single location, but by that not by the CI. Thus, we indeed should get rid of it in near future due to the mentioned reasons. I'd vote to take this effort as soon as we agreed on final handling of the driving functions. Then each driving function should exhibit its own docstring example for CI and further notebook examples and unit test functions are really helpful and required.

**Comment by mgeier** [comment]
This was resolved by #154.
