### ISSUE TITLE
Rename "nfchoa" -> "dca"?

### ISSUE THREAD

**Issue by mgeier** [sfstoolbox/sfs-python#85]
This has been done in the SSR (https://github.com/SoundScapeRenderer/ssr/pull/120), we could also do it here?

**Comment by fs446** [comment]
Still against it, since the term is very blurry. NFC-HOA can be seen as DCA, but other approaches that do DCA-like or related stuff are not necessarily linked to what we call NFC-HOA. So we'd end up in a category mismatch problem.

However, since we now have an ESA category, and NFC-HOA is in fact an ESA approach (as well as SDM), I think in future something like
`def sfs.frequency.esa.point_25D_circular_SSD()`
`def sfs.frequency.esa.point_3D_sphercial_SSD()`
could refer to what is currently 
`def sfs.frequency.nfchoa.point_25D`
`def sfs.frequency.nfchoa.point_3D`

IMO, there is no need to rename (the actually weird, but literature consolidated term) NFC-HOA to DCA (that by itself is not yet consistent) but to think about the ESA categorisation. This might look overcomplicated in first instance, but is elegantly concise in terms of the SFS theory.

We then could additionally open a DCA module to handle all algorithms that are _not exact_ modematching/ESA approaches.

**Comment by hagenw** [comment]
You have not introduced ESA, so I don't know what it mean.

But I agree that it would be nice to have one common name for the explicit solution. I was always bothered why I have to use different names for the explicit solutions presented in https://sfs.readthedocs.io/en/3.1.1/nfchoa/, only because of different geometries.

But of course historic names are known in the community and with new ones like ESA it can happen that you don't know them.

**Comment by fs446** [comment]
Sorry for not defining ESA, it's already in the docstring, but not appear here:
its the equivalent scattering approach, an approach where you can derive implicit driving functions from. These are equivalent with the explicit mode matching solutions in spherical, circular, planar, linear SSDs.

**Comment by mgeier** [comment]
I think the consensus was that we don't want to use "dca".
